config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  #capture the parent/child relationship in the routing
  resources :products do
  	resources :reviews 
  end



  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

	# :total_reviews, :int
 #    :product_name, :string
 #    :product_id, :int
# 	  :total_visits, :int
 #    :review_views, :int
 #    :total_sales, :int
 #    :review_to_sales, :int

	
	belongs_to :shop
	has_many :reviews, {dependent: :destroy, autosave: true}

end

app/models/review.rb
class Review < ApplicationRecord

	# t.datetime "created_at",                  
 #    t.datetime "updated_at",                  
 #    t.integer  "rating"
 #    t.text     "comment"
 #    t.string   "author_name"
 #    t.string   "author_email"
 #    t.text     "vendor_response"
 #    t.boolean  "response_resolved"
 #    t.datetime "solicit_review_at"
 #    t.boolean  "incorporated_into_aggregate"

	belongs_to :product 

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop #includes Session accessor & shop validation
  include ShopifyApp::SessionStorage #store and retrieve Sessions

  # t.string   "shopify_domain", null: false
  # t.string   "shopify_token",  null: false
  # t.datetime "created_at"
  # t.datetime "updated_at"

 has_many :products, {autosave: true, dependent: :destroy}


end

app/controllers/application_controller.rb
# 1. Create ability to receive & store reviews for particular products
# from within the admin panel 

# we're currently displaying reviews.  Need to accept reviews from the UI



class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController

	include DbHelper

  def index

  #Add new shop & products to database if they don't already exist there
  #once new shop is added populate database with shop's current products
  shopifyShop = ShopifyAPI::Shop.current
  localShop = Shop.find_by(shopify_domain: shopifyShop.domain)
  if (!localShop.isUpToDate)
    #updates the local database with the new shop's products
    populateLocalDatabase(localShop)
  end

  #Calls the shopify API therefore 'find all products' only returns this vendor's products
  @shopProducts = localShop.products

  end



end

app/controllers/products_controller.rb
class ProductsController < ShopifyApp::AuthenticatedController


	
end

app/controllers/reviews_controller.rb
class ReviewsController < ShopifyApp::AuthenticatedController

def new
end

def create
end



end

app/controllers/shops_controller.rb
class ShopsController < ShopifyApp::AuthenticatedController








end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/db_helper.rb
module DbHelper

	def TestDbHelper
		puts 'testing database helper'
	end


	#creates a new vendor in the local database from the current store
	#Stores store_id and domain
	def CreateLocalShop
		shopifyVendor = ShopifyAPI::Shop.current
		#save as new if vendor doesn't currently exist in the database
		
		newShop = Shop.new(shopify_domain: shopifyVendor.domain, name: shopifyVendor.name)
		newShop.save

	end


	#Call this method to populate the local db with test store products 
	def populateLocalDatabase(myShop)

		allShopProducts = ShopifyAPI::Product.find(:all);
		allShopProducts.each do |product|
			myProduct = Product.new(product_id: product.id, product_name: product.title, total_reviews: 0, total_visits: 0)
			myShop.products << myProduct
		end
		myShop.isUpToDate = true;
		myShop.save

	end

	# #Method to update local database of products with the shop's database, i.e. accounts for if the vendor edited their produdct list
	 #ideal situation would be to call this at the beginning of a Session, not very frequently
	 def updateLocalDatabase(currentUserStoreDomain)

		allShopProducts = ShopifyAPI::Product.find(:all)

		localShop = Shop.find_by(shopify_domain: currentUserStoreDomain)
		allLocalProducts = localShop.products

		#for each local product, check if a product exists in the shop's store with the same product id
		allLocalProducts.each do |val|
			#if product exists locally but not in Shopify's db
			if (!allShopProducts.any? { |entry| entry.id == val.product_id })
				#product exists locally but not at shop (product has been removed from the shop's store).
				 val.destroy
			end
		end

		allShopProducts.each do |val|
			#if product exists locally and not at shop
			if (!allLocalProducts.any? {|entry| entry.product_id == val.id })
				#product exists at shop but not locally (new product at shop). add into local database
				localVendor.products << Product.new(product_id: val.id, product_name: val.title, total_reviews: 0, total_visits: 0)
			end
		end
	end



end

app/helpers/products_helper.rb
module ProductsHelper


end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper

end

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Home",
        icon: "<%= asset_path('favicon.ico') %>"
      });
    });
  </script>
<% end %>

<h2>Products:</h2>
<ul>
<% @shopProducts.each do |product| %> 
	<li><%= product.product_name %> <br> 
	
	<%= render partial: 'reviews/review', collection: product.reviews %> 

	<%= render partial: 'products/accept_review', locals: {product: product} %> 
	</li>

<%end%> 
</ul>
<%# <%= link_to product.title, "https://#{@shop_session.url}/admin/products/#{product.id}", target: "_top" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewRad</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name.presence || 'Embedded Shopify App Example' %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: <%= Rails.env.development? || Rails.env.test? ? 'false' : 'true' %> 
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>

app/views/products/_accept_review.html.erb
<%= form_for(:review, url: product_reviews_path(product), method: "post") do |f| %>

	<% if @review %> <%#there will only even be a @review object anyway if there's a saving error %> 
		<% if @review.errors.any? %> 
			<%= render partial: 'shared/errors', locals: {errorObj: @review} %> 
		<%end%> 
	<%end%> 

	<%= f.number_field :rating, class: 'form-control' %> 
	<%= f.text_area :comment, class: 'form-control' %> 
	<%= f.submit "Post Review" %> 
<% end %> 

app/views/products/_product_details.html.erb
<%#need to provide an array of products call @products%>

<div class="product div">
  <% @products.each do |product| %>
  	<h3> <%= product.title %> </h3>
  	

    

app/views/products/index.html.erb
<%provide(:title, "All Products")%> 
<h2>Products:</h2>

  <% @shopProducts.each do |product| %> 
    <h3><%= product.product_name %> </h3><br> 
  	
  	<%= render partial: 'reviews/review', collection: product.reviews %> 
  	<%= render partial: 'products/accept_review', locals: {product: product} %> 


  <%end%> 

app/views/reviews/_review.html.erb
<% if(review) %>
	Rating: <%= review.rating %> <br> 
	Review:<%= review.comment %> <br> 
<% else %> 
	No reviews! 
<%end%>

app/views/shared/_errors.html.erb
<div class="error-explanation">
	<div class="alert alert-danger">
		<%= pluralize(locals[:errorObj].errors.count, 'error') %> 
	</div>
	<ul>
		<%locals[:errorObj].errors.full_messages.each do |msg| %> 
			<li> <%= msg %> </li>
		<% end %> 
	</ul>
</div>